efs/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

urlpatterns = [
    path('', include('portfolio.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    # re_path(r'^accounts/login/$', LoginView.as_view(template_name='registration/login.html'), name="login"),
    # re_path(r'^accounts/logout/$', LogoutView.as_view(), LogoutView.next_page, name="logout"),

]

portfolio/urls.py
from django.conf.urls import url
from portfolio import views
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from rest_framework.urlpatterns import format_suffix_patterns

app_name = 'portfolio'
urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'^home/$', views.home, name='home'),
    path('customer_list', views.customer_list, name='customer_list'),
    path('customer/<int:pk>/edit/', views.customer_edit, name='customer_edit'),
    path('customer/<int:pk>/delete/', views.customer_delete, name='customer_delete'),
    path('customer/create/', views.customer_new, name='customer_new'),

    path('stock_list', views.stock_list, name='stock_list'),
    path('stock/create/', views.stock_new, name='stock_new'),
    path('stock/<int:pk>/edit/', views.stock_edit, name='stock_edit'),
    path('stock/<int:pk>/delete/', views.stock_delete, name='stock_delete'),

    path('investment_list', views.investment_list, name='investment_list'),
    path('investment/create/', views.investment_new, name='investment_new'),
    path('investment/<int:pk>/edit/', views.investment_edit, name='investment_edit'),
    path('investment/<int:pk>/delete/', views.investment_delete, name='investment_delete'),

    path('accounts/password_reset/',
         auth_views.PasswordResetView.as_view(template_name="registration/password_reset.html"), name='password_reset'),
    path('accounts/password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name="registration/reset_email_sent.html"),
         name='reset_email_sent'),
    path('accounts/reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="registration/reset_confirm.html"),
         name='reset_confirm'),
    path('accounts/reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name="registration/reset_complete.html"),
         name='reset_complete'),

    path('accounts/password_change/',
         auth_views.PasswordChangeView.as_view(template_name="registration/password_change.html"),
         name='password_change'),
    path('accounts/password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name="registration/password_changed.html"),
         name='password_changed'),
    path('customer/<int:pk>/portfolio/', views.portfolio, name='portfolio'),
    path('customers_json/', views.CustomerList.as_view()),
    path('signup/', views.AdvisorSignUp, name='signup'),
    path('signup/signup_successful', views.signup_successful, name='signup_successful'),
    path('customer/<int:pk>/portfolio/portfolio_pdf/', views.portfolio_pdf, name='portfolio_pdf'),
]

portfolio/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
import requests


# Create your models here.
class Customer(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=200)
    cust_number = models.IntegerField(blank=False, null=False)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=10)
    email = models.EmailField(max_length=200)
    cell_phone = models.CharField(max_length=50)
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.cust_number)


class Investment(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='investments')
    category = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    acquired_value = models.DecimalField(max_digits=10, decimal_places=2)
    acquired_date = models.DateField(default=timezone.now)
    recent_value = models.DecimalField(max_digits=10, decimal_places=2)
    recent_date = models.DateField(default=timezone.now, blank=True, null=True)

    def created(self):
        self.acquired_date = timezone.now()
        self.save()

    def updated(self):
        self.recent_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.customer)

    def results_by_investment(self):
        return self.recent_value - self.acquired_value


class Stock(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='stocks')
    symbol = models.CharField(max_length=10)
    name = models.CharField(max_length=50)
    shares = models.DecimalField(max_digits=10, decimal_places=1)
    purchase_price = models.DecimalField(max_digits=10, decimal_places=2)
    purchase_date = models.DateField(default=timezone.now, blank=True, null=True)

    def created(self):
        self.recent_date = timezone.now()
        self.save()

    def initial_stock_value(self):
        return self.shares * self.purchase_price

    def current_stock_price(self):
        symbol_f = str(self.symbol)
        main_api = 'http://api.marketstack.com/v1/eod?'
        api_key = 'access_key=39d3923811b493115c3189ed15e38417&limit=1&symbols='
        url = main_api + api_key + symbol_f
        json_data = requests.get(url).json()
        open_price = float(json_data["data"][0]["open"])
        share_value = open_price
        return share_value

    def current_stock_value(self):
        return float(self.current_stock_price()) * float(self.shares)

    def __str__(self):
        return str(self.customer)

portfolio/forms.py
from django import forms
from .models import Customer, Stock, Investment
from django.forms.widgets import DateInput, DateTimeInput
from django.contrib.auth.forms import UserCreationForm
from .models import *


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('cust_number', 'name', 'address', 'city', 'state', 'zipcode', 'email', 'cell_phone',)


class StockForm(forms.ModelForm):
    class Meta:
        model = Stock
        fields = ('customer', 'symbol', 'name', 'shares', 'purchase_price', 'purchase_date',)
        widgets = {'purchase_date': DateInput(attrs={'type': 'date'}),
        }


class InvestmentForm(forms.ModelForm):
    class Meta:
        model = Investment
        fields = ('customer', 'category', 'description', 'acquired_value', 'acquired_date', 'recent_value',
                  'recent_date',)
        widgets = {'acquired_date': DateInput(attrs={'type': 'date'}),
                   'recent_date': DateInput(attrs={'type': 'date'}),
        }


class SignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "email", "password1", "password2")

portfolio/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.template.loader import get_template
from .models import *
from .forms import *
from django.shortcuts import redirect
from django.db.models import Sum
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import CustomerSerializer
from django.views.generic import CreateView, ListView
from django.conf import settings
from django.http import HttpResponse
from django.views.generic import View
from .utils import render_to_pdf

now = timezone.now()


def home(request):
    return render(request, 'portfolio/home.html', {'portfolio': home})


@login_required
def customer_list(request):
    customer = Customer.objects.filter(created_date__lte=timezone.now())
    return render(request, 'portfolio/customer_list.html',
                  {'customers': customer})


@login_required
def customer_edit(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    if request.method == "POST":
        # update
        form = CustomerForm(request.POST, instance=customer)
        if form.is_valid():
            customer = form.save(commit=False)
            customer.updated_date = timezone.now()
            customer.save()
            customer = Customer.objects.filter(created_date__lte=timezone.now())
            return render(request, 'portfolio/customer_list.html', {'customers': customer})
    else:
        # edit
        form = CustomerForm(instance=customer)
        return render(request, 'portfolio/customer_edit.html', {'form': form})


@login_required
def customer_delete(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    customer.delete()
    return redirect('portfolio:customer_list')


@login_required
def portfolio(request, pk):
    return render(request, 'portfolio/portfolio.html', {})


@login_required
def stock_list(request):
    stocks = Stock.objects.filter(purchase_date__lte=timezone.now())
    return render(request, 'portfolio/stock_list.html', {'stocks': stocks})


@login_required
def stock_new(request):
    if request.method == "POST":
        form = StockForm(request.POST)
        if form.is_valid():
            stock = form.save(commit=False)
            stock.created_date = timezone.now()
            stock.save()
            stocks = Stock.objects.filter(purchase_date__lte=timezone.now())
            return render(request, 'portfolio/stock_list.html',
                          {'stocks': stocks})
    else:
        form = StockForm()
    return render(request, 'portfolio/stock_new.html', {'form': form})


@login_required
def stock_edit(request, pk):
    stock = get_object_or_404(Stock, pk=pk)
    if request.method == "POST":
        form = StockForm(request.POST, instance=stock)
        if form.is_valid():
            stock = form.save()
            # stock.customer = stock.id
            stock.updated_date = timezone.now()
            stock.save()
            stocks = Stock.objects.filter(purchase_date__lte=timezone.now())
            return render(request, 'portfolio/stock_list.html', {'stocks': stocks})
    else:
        form = StockForm(instance=stock)
    return render(request, 'portfolio/stock_edit.html', {'form': form})


@login_required
def stock_delete(request, pk):
    stock = get_object_or_404(Stock, pk=pk)
    stock.delete()
    return redirect('portfolio:stock_list')


@login_required
def investment_new(request):
    if request.method == "POST":
        form = InvestmentForm(request.POST)
        if form.is_valid():
            investment = form.save(commit=False)
            investment.created_date = timezone.now()
            investment.save()
            investment = Investment.objects.filter(acquired_date__lte=timezone.now())
            return render(request, 'portfolio/investment_list.html',
                          {'investments': investment})
    else:
        form = InvestmentForm()
    return render(request, 'portfolio/investment_new.html', {'form': form})


@login_required
def investment_list(request):
    investments = Investment.objects.filter(acquired_date__lte=timezone.now())
    return render(request, 'portfolio/investment_list.html', {'investments': investments})


@login_required
def investment_edit(request, pk):
    investment = get_object_or_404(Investment, pk=pk)
    if request.method == "POST":
        # update
        form = InvestmentForm(request.POST, instance=investment)
        if form.is_valid():
            investment = form.save()
            investment.updated_date = timezone.now()
            investment.save()
            investments = Investment.objects.filter(acquired_date__lte=timezone.now())
            return render(request, 'portfolio/investment_list.html', {'investments': investments})
    else:
        # edit
        form = InvestmentForm(instance=investment)
    return render(request, 'portfolio/investment_edit.html', {'form': form})


@login_required
def investment_delete(request, pk):
    investment = get_object_or_404(Investment, pk=pk)
    investment.delete()
    return redirect('portfolio:investment_list')


@login_required
def customer_new(request):
    if request.method == "POST":
        form = CustomerForm(request.POST)
        if form.is_valid():
            customer = form.save(commit=False)
            customer.created_date = timezone.now()
            customer.save()
            customer = Customer.objects.filter(created_date__lte=timezone.now())
            return render(request, 'portfolio/customer_list.html',
                          {'customers': customer})
    else:
        form = CustomerForm()
    return render(request, 'portfolio/customer_new.html', {'form': form})


@login_required
def portfolio(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    customers = Customer.objects.filter(created_date__lte=timezone.now())
    investments = Investment.objects.filter(customer=pk)
    stocks = Stock.objects.filter(customer=pk)
    sum_recent_value = Investment.objects.filter(customer=pk).aggregate(Sum('recent_value'))
    sum_acquired_value = Investment.objects.filter(customer=pk).aggregate(Sum('acquired_value'))
    # overall_investment_results = sum_recent_value-sum_acquired_value
    # Initialize the value of the stocks
    sum_current_stocks_value = 0
    sum_of_initial_stock_value = 0
    sum_current_investment_value = 0
    sum_of_initial_investment_value = 0

    # Loop through each stock and add the value to the total
    for stock in stocks:
        sum_current_stocks_value += stock.current_stock_value()
        sum_of_initial_stock_value += stock.initial_stock_value()

    for investment in investments:
        sum_current_investment_value += investment.recent_value
        sum_of_initial_investment_value += investment.acquired_value

    return render(request, 'portfolio/portfolio.html', {'customers': customers,
                                                        'investments': investments,
                                                        'stocks': stocks,
                                                        'sum_acquired_value': sum_acquired_value,
                                                        'sum_recent_value': sum_recent_value,
                                                        'sum_current_stocks_value': sum_current_stocks_value,
                                                        'sum_of_initial_stock_value': sum_of_initial_stock_value,})


# List at the end of the views.py
# Lists all customers
class CustomerList(APIView):
    def get(self, request):
        customers_json = Customer.objects.all()
        serializer = CustomerSerializer(customers_json, many=True)
        return Response(serializer.data)


def signup_successful(request):
    return render(request, 'registration/signup_successful.html', {'portfolio': signup_successful})


def AdvisorSignUp(request):
    form = SignUpForm()
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('portfolio:signup_successful')
        else:
            context = {'form': form}
            return render(request, 'registration/signup_form.html', context)
    else:
        context = {'form': form}
        return render(request, 'registration/signup_form.html', context)


@login_required
def portfolio_pdf(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    customers = Customer.objects.filter(created_date__lte=timezone.now())
    investments = Investment.objects.filter(customer=pk)
    stocks = Stock.objects.filter(customer=pk)
    sum_recent_value = Investment.objects.filter(customer=pk).aggregate(Sum('recent_value'))
    sum_acquired_value = Investment.objects.filter(customer=pk).aggregate(Sum('acquired_value'))
    # overall_investment_results = sum_recent_value-sum_acquired_value
    # Initialize the value of the stocks
    sum_current_stocks_value = 0
    sum_of_initial_stock_value = 0

    # Loop through each stock and add the value to the total
    for stock in stocks:
        sum_current_stocks_value += stock.current_stock_value()
        sum_of_initial_stock_value += stock.initial_stock_value()

    template = get_template('portfolio/portfolio_pdf.html')
    context = {'customers': customers,
               'investments': investments,
               'stocks': stocks,
               'sum_acquired_value': sum_acquired_value,
               'sum_recent_value': sum_recent_value,
               'sum_current_stocks_value': sum_current_stocks_value,
               'sum_of_initial_stock_value': sum_of_initial_stock_value,
    }
    html = template.render(context)
    pdf = render_to_pdf('portfolio/portfolio_pdf.html', context)
    if pdf:
        response = HttpResponse(pdf, content_type='application/pdf')
        filename = "Customers_%s.pdf" %("portfolio")

portfolio/templates/portfolio/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>base</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
            crossorigin="anonymous"></script>
 <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }
        /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
        .row.content {
            height: 450px
        }

        /* Set gray background color and 100% height */
        .sidenav {
            padding-top: 20px;
            background-color: #f1f1f1;
            height: 100%;
        }

        /* Set black background color, white text and some padding */
        footer {
            background-color: #555;
            color: white;
            padding: 15px;
        }

        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
            .sidenav {
                height: auto;
                padding: 15px;
            }

            .row.content {
                height: auto;
            }
        }
    </style>
</head>
<body id="app-layout">

<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'portfolio:home' %}">Eagle Financial Services</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'portfolio:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'portfolio:customer_list' %}">Customers<span
                        class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'portfolio:investment_list' %}">Investments<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'portfolio:stock_list' %}">Stocks<span class="sr-only">(current)</span></a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            {% if user.is_authenticated %}
            <a href="{% url 'portfolio:password_change' %}" class="btn btn-secondary ml-2">Change
                password</a>
            <a href="{% url 'logout' %}" class="btn btn-secondary ml-2">Logout</a>
            {% else %}
            <a href="{% url 'login' %}" class="btn btn-secondary ml-2" role="button"
               aria-pressed="true">login</a>
            <a href="{% url 'portfolio:signup' %}" class="btn btn-secondary ml-2" role="button"
               aria-pressed="true">Signup</a>
            {% endif %}
        </form>
        </ul>
    </div>
</nav>
<br>
<br>
<div class="content container">
    <div class="row">
        <div class="col-md-8">
            {% block content %}
                <div class="links">
                    <!-- Example row of columns -->
                    <div class="row">
                        <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static 'images/customer.jpg' %}" alt="customer" style="width:500px;height:600px;">
                                <div class="caption">
                                    <h2>Customer</h2>
                                    <p>We see our success in our customers success, it gives us an immense pleasure when
                                        our
                                        advises
                                        turn out to be fruitful. </p>
                                    {% if user.is_authenticated %}
                                        <p><a class="btn btn-default" href="{% url 'portfolio:customer_list' %}"
                                              role="button">View
                                            details &raquo;</a></p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static 'images/nonstock.jpg' %}" alt="non-stock"/>
                                <div class="caption">
                                    <h2>Non-Stock Investments</h2>
                                    <p>Our team also provides advises for Non-Stock investments.</p>
                                    <p><a class="btn btn-default" href="{% url 'portfolio:investment_list' %}"
                                           role="button">View
                                        details &raquo;</a></p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static 'images/stocks.jpg' %}" alt="stocks"/>
                                <div class="caption">
                                    <h2>Stock Portfolio</h2>
                                    <p>Our Stock portfolios vary across industries.</p>
                                    <p><a class="btn btn-default" href="{% url 'portfolio:customer_list' %}" role="button">View
                                        details &raquo;</a></p>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

portfolio/templates/portfolio/customer_delete.html
{% block body_block %}
<h1>Delete {{ customer.name }}?</h1>
<form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'portfolio:home' pk=customer.cust_number %} ">Cancel</a>
</form>
{% endblock %}

portfolio/templates/portfolio/customer_edit.html
{% extends 'portfolio/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}
<h1>Edit Customer</h1>
<br>
<form method="POST" class="customer-form">{% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="save btn btn-primary">Update</button>
</form>
{% endblock %}

portfolio/templates/portfolio/customer_list.html
{% extends 'portfolio/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}
<html>
<head>
    <meta charset="UTF-8">
    <title>Eagle Financial</title>
</head>
<body>
<style>
    body {
        background-color: beige;
    }
</style>

<div class="container">
    <div class="row">
            <div class="panel panel-primary">
                <h2 style="text-align: center;">Welcome!</h2>
                <h3 style="text-align: center;">
                    Eagle Financial Services, your Midwest Financial Services Partner.
                </h3>
                <br>
                <br>
            </div>
    </div>
</div>
<div class="row">
    <h2 style="padding-left: 15Px"><u>Customer Information</u><br></h2>

</div>
<div>
    <table>
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr class="bg-info">
            <th>Customer Number</th>
            <th>Name</th>
            <th>Address</th>
            <th>City</th>
            <th>State</th>
            <th>Zip</th>
            <th>Primary Email</th>
            <th>Cell Phone</th>
            <th colspan="4">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for customer in customers %}
        <tr>
            <td>{{ customer.cust_number }}</td>
            <td>{{ customer.name }}</td>
            <td>{{ customer.address }}</td>
            <td>{{ customer.city }}</td>
            <td>{{ customer.state }}</td>
            <td>{{ customer.zipcode }}</td>
            <td>{{ customer.email }}</td>
            <td>{{ customer.cell_phone }}</td>
            <td><a href="{% url 'portfolio:customer_edit' pk=customer.pk %}" class="btn btn-warning">Edit</a>
            <td><a href="{% url 'portfolio:customer_delete' pk=customer.pk %}"
                   onclick="return confirm('Are you sure you want to delete?')"
                   class="btn btn-danger">Delete</a>
            </td>
            <td><a href="{% url 'portfolio:portfolio' pk=customer.pk %}"
                   class="btn btn-primary">Portfolio</a>
            <td><a href="{% url 'portfolio:portfolio_pdf' pk=customer.pk %}"
                   class="btn btn-primary">Pdf_Report</a>

        </tr>
        {% endfor %}
        </tbody>
    </table>

    <div class="row">
        <a href="{% url 'portfolio:customer_new' %}" class="row"><span
                class="btn btn-primary">Add Customer</span></a>
    </div>
    </table>
</div>
</body>
</html>
{% endblock %}

portfolio/templates/portfolio/investment_list.html
{% extends 'portfolio/base.html' %}
{% block content %}
<html lang="en">
<body>
<style>
    body {
        background-color: beige;
    }
</style>
<div class="container">
    <div class="row">
            <div class="panel panel-primary">
                <h2 style="text-align: center;">Welcome!</h2>
                <h3 style="text-align: center;">
                    Eagle Financial Services, your Midwest Financial Services Partner.
                </h3>
                <br>
                <br>
            </div>
    </div>
</div>
<div class="row">
    <h2 style="padding-left: 15Px"><u>Investment Information</u></h2>
</div>
<div>
    <table class="table table-hover table-responsive-lg text-center">
        <thead>
        <tr class="bg-info">
            <th>Customer number</th>
            <th>Category</th>
            <th>Description</th>
            <th>Acquired Value</th>
            <th>Acquired Date</th>
            <th>Recent Value</th>
            <th>Recent Date</th>
            <th colspan="3">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for investment in investments %}
        <tr>
            <td>{{ investment.customer }}</td>
            <td>{{ investment.category }}</td>
            <td>{{ investment.description }}</td>
            <td>{{ investment.acquired_value }}</td>
            <td>{{ investment.acquired_date }}</td>
            <td>{{ investment.recent_value }}</td>
            <td>{{ investment.recent_date }}</td>
            <td><a href="{% url 'portfolio:investment_edit' pk=investment.pk %}"
                   class="btn btn-warning">Edit</a>
            <td><a href="{% url 'portfolio:investment_delete' pk=investment.pk %}"
                   onclick="return confirm('Are you sure you want to delete?')"
                   class="btn btn-danger">Delete</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="row">
        <a href="{% url 'portfolio:investment_new' %}" class="row"><span
                class="btn btn-primary">Add Investment</span></a>
    </div>
</div>

</body>
</html>
{% endblock %}

portfolio/templates/portfolio/stock_list.html
{% extends 'portfolio/base.html' %}
{% block content %}
<html>
<head>
    <meta charset="UTF-8">
    <title>Eagle Financial</title>
</head>
<body>
<style>
    body {
        background-color: beige;
    }
</style>
<div class="container">
    <div class="row">
            <div class="panel panel-primary">
                <h2 style="text-align: center;">Welcome!</h2>
                <h3 style="text-align: center;">
                    Eagle Financial Services, your Midwest Financial Services Partner.
                </h3>
                <br>
                <br>
            </div>
    </div>
</div>
<div class="row">
    <h2 style="padding-left: 15Px"><u>Stocks Information</u></h2>
</div>
<div>
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr class="bg-info">
            <th>Customer number</th>
            <th>Symbol</th>
            <th>Name</th>
            <th>Shares</th>
            <th>Purchase Price</th>
            <th>Purchase Date</th>
            <th colspan="3">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for stock in stocks %}
        <tr>
            <td>{{ stock.customer }}</td>
            <td>{{ stock.symbol }}</td>
            <td>{{ stock.name }}</td>
            <td>{{ stock.shares }}</td>
            <td>{{ stock.purchase_price }}</td>
            <td>{{ stock.purchase_date }}</td>
            <td><a href="{% url 'portfolio:stock_edit' pk=stock.pk %}"
                   class="btn btn-warning">Edit</a></td>
            <td><a href="{% url 'portfolio:stock_delete' pk=stock.pk %}"
                   onclick="return confirm('Are you sure you want to delete?')"
                   class="btn btn-danger">Delete</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="row">
        <a href="{% url 'portfolio:stock_new' %}" class="row"><span
                class="btn btn-primary">Add Stock</span></a>
    </div>
</div>
</body>
</html>
{% endblock %}